const teamNames = [
    "Anaheim Ducks",
    "Arizona Coyotes",
    "Boston Bruins",
    "Buffalo Sabres",
    "Carolina Hurricanes",
    "Columbus Blue Jackets",
    "Calgary Flames",
    "Chicago Blackhawks",
    "Colorado Avalanche",
    "Dallas Stars",
    "Detroit Red Wings",
    "Edmonton Oilers",
    "Florida Panthers",
    "Los Angeles Kings",
    "Minnesota Wild",
    "Montréal Canadiens",
    "New Jersey Devils",
    "Nashville Predators",
    "New York Islanders",
    "New York Rangers",
    "Ottawa Senators",
    "Philadelphia Flyers",
    "Pittsburgh Penguins",
    "Seattle Kraken",
    "San Jose Sharks",
    "St Louis Blues",
    "Tampa Bay Lightning",
    "Toronto Maple Leafs",
    "Vancouver Canucks",
    "Vegas Golden Knights",
    "Winnipeg Jets",
    "Washington Capitals"
];

export default teamNames;